version: '3.8'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: mac
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  web-1:
    image: application-2
    expose:
      - 8080
    depends_on:
      - db

  web-2:
    image: application-2
    expose:
      - 8080
    depends_on:
      - db

  web-3:
    image: application-2
    expose:
      - 8080
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-1
      - web-2
      - web-3
